### ISSUE TITLE
Introduction for Codecs / Audio

### ISSUE THREAD

**Issue by pmaness** [Dash-Industry-Forum/Codecs#3]
Suggested text to replace "tbd":

The following Table is a list of audio codecs and profiles that are CMAF compliant and are defined for use in systems adhering to the DASH-IF IOP-V5 specifications. Additional codecs and profiles that do not have a fully defined CMAF binding, but might still be usable in some CMAF systems, are defined in the IOP Version 4.3 Audio Amendment.

**Comment by haudiobe** [comment]
Addressed
